### ISSUE TITLE
Is it only for Unix?

### ISSUE THREAD

**Issue by useragent23253** [0xor0ne/recmd#2]
Hello, I can't to compile it from windows. Is it only for Unix based systems?
`cargo check
   Compiling version_check v0.9.4
   Compiling typenum v1.16.0
    Checking cfg-if v1.0.0
   Compiling proc-macro2 v1.0.51
   Compiling unicode-ident v1.0.6
   Compiling quote v1.0.23
    Checking cpufeatures v0.2.5
   Compiling syn v1.0.107
    Checking subtle v2.4.1
   Compiling memchr v2.5.0
    Checking zeroize v1.5.7
   Compiling libc v0.2.139
   Compiling argh_shared v0.1.10
    Checking opaque-debug v0.3.0
    Checking minimal-lexical v0.2.1
    Checking hex v0.4.3
    Checking byteorder v1.4.3
    Checking bytes v1.4.0
    Checking shell-words v1.1.0
    Checking getrandom v0.2.8
   Compiling generic-array v0.14.6
    Checking rand_core v0.6.4
    Checking daemonize v0.5.0
error[E0433]: failed to resolve: could not find `unix` in `os`
  --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:55:14
   |
55 | use std::os::unix::ffi::OsStringExt;
   |              ^^^^ could not find `unix` in `os`

error[E0433]: failed to resolve: could not find `unix` in `os`
  --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:56:14
   |
56 | use std::os::unix::io::AsRawFd;
   |              ^^^^ could not find `unix` in `os`

error[E0433]: failed to resolve: could not find `uid_t` in `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:396:74
    |
396 |                         (Some(pid), None, Some(gid)) => Some((pid, libc::uid_t::MAX - 1, gid)),
    |                                                                          ^^^^^ could not find `uid_t` in `libc`

error[E0433]: failed to resolve: could not find `gid_t` in `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:397:79
    |
397 |                         (Some(pid), Some(uid), None) => Some((pid, uid, libc::gid_t::MAX - 1)),
    |                                                                               ^^^^^ could not find `gid_t` in `libc`

error[E0412]: cannot find type `uid_t` in crate `libc`
  --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:67:14
   |
67 |     Id(libc::uid_t),
   |              ^^^^^ not found in `libc`

error[E0412]: cannot find type `uid_t` in crate `libc`
  --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:87:44
   |
87 |             inner: UserImpl::Id(t as libc::uid_t),
   |                                            ^^^^^ not found in `libc`

error[E0412]: cannot find type `gid_t` in crate `libc`
  --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:95:14
   |
95 |     Id(libc::gid_t),
   |              ^^^^^ not found in `libc`

error[E0412]: cannot find type `gid_t` in crate `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:115:45
    |
115 |             inner: GroupImpl::Id(t as libc::gid_t),
    |                                             ^^^^^ not found in `libc`

error[E0412]: cannot find type `mode_t` in crate `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:123:18
    |
123 |     inner: libc::mode_t,
    |                  ^^^^^^ not found in `libc`

error[E0412]: cannot find type `mode_t` in crate `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:129:35
    |
129 |             inner: inner as libc::mode_t,
    |                                   ^^^^^^ not found in `libc`

error[E0425]: cannot find function `umask` in crate `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:375:19
    |
375 |             libc::umask(self.umask.inner);
    |                   ^^^^^ not found in `libc`

error[E0412]: cannot find type `uid_t` in crate `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:393:50
    |
393 |                 let args: Option<(PathBuf, libc::uid_t, libc::gid_t)> =
    |                                                  ^^^^^ not found in `libc`

error[E0412]: cannot find type `gid_t` in crate `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:393:63
    |
393 |                 let args: Option<(PathBuf, libc::uid_t, libc::gid_t)> =
    |                                                               ^^^^^ not found in `libc`

error[E0412]: cannot find type `pid_t` in crate `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:434:49
    |
434 | unsafe fn perform_fork() -> Result<Option<libc::pid_t>, ErrorKind> {
    |                                                 ^^^^^ not found in `libc`

error[E0425]: cannot find function `fork` in crate `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:435:31
    |
435 |     let pid = check_err(libc::fork(), ErrorKind::Fork)?;
    |                               ^^^^ not found in `libc`

error[E0412]: cannot find type `pid_t` in crate `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:443:30
    |
443 | unsafe fn waitpid(pid: libc::pid_t) -> Result<libc::c_int, ErrorKind> {
    |                              ^^^^^ not found in `libc`

error[E0425]: cannot find function `waitpid` in crate `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:445:22
    |
445 |      check_err(libc::waitpid(pid, &mut child_ret, 0), ErrorKind::Wait)?;
    |                      ^^^^^^^ not found in `libc`

error[E0425]: cannot find function `setsid` in crate `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:450:21
    |
450 |     check_err(libc::setsid(), ErrorKind::DetachSession)?;
    |                     ^^^^^^ help: a function with a similar name exists: `getpid`
    |
   ::: C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\libc-0.2.139\src\windows\mod.rs:486:5
    |
486 |     pub fn getpid() -> ::c_int;
    |     -------------------------- similarly named function `getpid` defined here

error[E0425]: cannot find value `STDIN_FILENO` in crate `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:478:25
    |
478 |     process_stdio(libc::STDIN_FILENO, stdin)?;
    |                         ^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `STDOUT_FILENO` in crate `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:479:25
    |
479 |     process_stdio(libc::STDOUT_FILENO, stdout)?;
    |                         ^^^^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find value `STDERR_FILENO` in crate `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:480:25
    |
480 |     process_stdio(libc::STDERR_FILENO, stderr)?;
    |                         ^^^^^^^^^^^^^ not found in `libc`

error[E0412]: cannot find type `gid_t` in crate `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:487:51
    |
487 | unsafe fn get_group(group: Group) -> Result<libc::gid_t, ErrorKind> {
    |                                                   ^^^^^ not found in `libc`

error[E0412]: cannot find type `gid_t` in crate `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:500:34
    |
500 | unsafe fn set_group(group: libc::gid_t) -> Result<(), ErrorKind> {
    |                                  ^^^^^ not found in `libc`

error[E0425]: cannot find function `setgid` in crate `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:501:21
    |
501 |     check_err(libc::setgid(group), ErrorKind::SetGroup)?;
    |                     ^^^^^^ help: a function with a similar name exists: `getpid`
    |
   ::: C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\libc-0.2.139\src\windows\mod.rs:486:5
    |
486 |     pub fn getpid() -> ::c_int;
    |     -------------------------- similarly named function `getpid` defined here

error[E0412]: cannot find type `uid_t` in crate `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:505:48
    |
505 | unsafe fn get_user(user: User) -> Result<libc::uid_t, ErrorKind> {
    |                                                ^^^^^ not found in `libc`

error[E0412]: cannot find type `uid_t` in crate `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:518:32
    |
518 | unsafe fn set_user(user: libc::uid_t) -> Result<(), ErrorKind> {
    |                                ^^^^^ not found in `libc`

error[E0425]: cannot find function `setuid` in crate `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:519:21
    |
519 |     check_err(libc::setuid(user), ErrorKind::SetUser)?;
    |                     ^^^^^^ help: a function with a similar name exists: `getpid`
    |
   ::: C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\libc-0.2.139\src\windows\mod.rs:486:5
    |
486 |     pub fn getpid() -> ::c_int;
    |     -------------------------- similarly named function `getpid` defined here

error[E0425]: cannot find function `flock` in crate `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:532:15
    |
532 |         libc::flock(fd, libc::LOCK_EX | libc::LOCK_NB),
    |               ^^^^^ not found in `libc`

error[E0425]: cannot find value `LOCK_EX` in crate `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:532:31
    |
532 |         libc::flock(fd, libc::LOCK_EX | libc::LOCK_NB),
    |                               ^^^^^^^ not found in `libc`

error[E0425]: cannot find value `LOCK_NB` in crate `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:532:47
    |
532 |         libc::flock(fd, libc::LOCK_EX | libc::LOCK_NB),
    |                                               ^^^^^^^ not found in `libc`

error[E0412]: cannot find type `uid_t` in crate `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:540:16
    |
540 |     uid: libc::uid_t,
    |                ^^^^^ not found in `libc`

error[E0412]: cannot find type `gid_t` in crate `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:541:16
    |
541 |     gid: libc::gid_t,
    |                ^^^^^ not found in `libc`

error[E0425]: cannot find function `chown` in crate `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:545:15
    |
545 |         libc::chown(path_c.as_ptr(), uid, gid),
    |               ^^^^^ not found in `libc`

error[E0425]: cannot find function `ftruncate` in crate `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:556:21
    |
556 |     check_err(libc::ftruncate(fd, 0), ErrorKind::TruncatePidfile)?;
    |                     ^^^^^^^^^ help: a function with a similar name exists: `strncat`
    |
   ::: C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\libc-0.2.139\src\windows\mod.rs:356:5
    |
356 |     pub fn strncat(s: *mut c_char, ct: *const c_char, n: size_t) -> *mut c_char;
    |     --------------------------------------------------------------------------- similarly named function `strncat` defined here

error[E0425]: cannot find function `fcntl` in crate `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:572:37
    |
572 |         let flags = check_err(libc::fcntl(fd, libc::F_GETFD), ErrorKind::GetPidfileFlags)?;
    |                                     ^^^^^ not found in `libc`

error[E0425]: cannot find value `F_GETFD` in crate `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:572:53
    |
572 |         let flags = check_err(libc::fcntl(fd, libc::F_GETFD), ErrorKind::GetPidfileFlags)?;
    |                                                     ^^^^^^^ not found in `libc`

error[E0425]: cannot find function `fcntl` in crate `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:575:19
    |
575 |             libc::fcntl(fd, libc::F_SETFD, flags | libc::FD_CLOEXEC),
    |                   ^^^^^ not found in `libc`

error[E0425]: cannot find value `F_SETFD` in crate `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:575:35
    |
575 |             libc::fcntl(fd, libc::F_SETFD, flags | libc::FD_CLOEXEC),
    |                                   ^^^^^^^ not found in `libc`

error[E0425]: cannot find value `FD_CLOEXEC` in crate `libc`
   --> C:\Users\admin\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:575:58
    |
575 |             libc::fcntl(fd, libc::F_SETFD, flags | libc::FD_CLOEXEC),
    |                                                          ^^^^^^^^^^ not found in `libc`

error[E0425]: cannot find function `ioctl` in crate `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:579:25
    |
579 |         check_err(libc::ioctl(fd, libc::FIOCLEX), ErrorKind::SetPidfileFlags)?;
    |                         ^^^^^ not found in `libc`

error[E0425]: cannot find value `FIOCLEX` in crate `libc`
   --> C:\Users\admin\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:579:41
    |
579 |         check_err(libc::ioctl(fd, libc::FIOCLEX), ErrorKind::SetPidfileFlags)?;
    |                                         ^^^^^^^ not found in `libc`

error[E0425]: cannot find function `chroot` in crate `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:586:21
    |
586 |     check_err(libc::chroot(path_c.as_ptr()), ErrorKind::Chroot)?;
    |                     ^^^^^^ not found in `libc`

error[E0412]: cannot find type `gid_t` in crate `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:590:59
    |
590 | unsafe fn get_gid_by_name(name: &CString) -> Option<libc::gid_t> {
    |                                                           ^^^^^ not found in `libc`

error[E0425]: cannot find function `getgrnam` in crate `libc`
   --> C:\Users\admin\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:591:21
    |
591 |     let ptr = libc::getgrnam(name.as_ptr() as *const libc::c_char);
    |                     ^^^^^^^^ not found in `libc`

error[E0412]: cannot find type `uid_t` in crate `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:600:59
    |
600 | unsafe fn get_uid_by_name(name: &CString) -> Option<libc::uid_t> {
    |                                                           ^^^^^ not found in `libc`

error[E0425]: cannot find function `getpwnam` in crate `libc`
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:601:21
    |
601 |     let ptr = libc::getpwnam(name.as_ptr() as *const libc::c_char);
    |                     ^^^^^^^^ not found in `libc`

error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:323:46
    |
323 |         let mut new: Daemonize<N> = unsafe { transmute(self) };
    |                                              ^^^^^^^^^
    |
    = note: source type: `Daemonize<T>` (size can vary because of [type error])
    = note: target type: `Daemonize<N>` (size can vary because of [type error])

error[E0599]: no method named `as_raw_fd` found for struct `File` in the current scope
   --> C:\Users\admin\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:470:35
    |
470 |                 let raw_fd = file.as_raw_fd();
    |                                   ^^^^^^^^^ method not found in `File`

error[E0308]: mismatched types
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:559:64
    |
559 |         libc::write(fd, pid_c.as_ptr() as *const libc::c_void, pid_length),
    |         ----------- arguments to this function are incorrect   ^^^^^^^^^^ expected `u32`, found `usize`
    |
note: function defined here
   --> C:\Users\admin\.cargo\registry\src\github.com-1ecc6299db9ec823\libc-0.2.139\src\windows\mod.rs:502:12
    |
502 |     pub fn write(fd: ::c_int, buf: *const ::c_void, count: ::c_uint) -> ::c_int;
    |            ^^^^^
help: you can convert a `usize` to a `u32` and panic if the converted value doesn't fit
    |
559 |         libc::write(fd, pid_c.as_ptr() as *const libc::c_void, pid_length.try_into().unwrap()),
    |                                                                          ++++++++++++++++++++

error[E0308]: mismatched types
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:563:18
    |
563 |     if written < pid_length as isize {
    |                  ^^^^^^^^^^^^^^^^^^^ expected `i32`, found `isize`
    |
help: you can convert an `isize` to an `i32` and panic if the converted value doesn't fit
    |
563 |     if written < (pid_length as isize).try_into().unwrap() {
    |                  +                   +++++++++++++++++++++

error[E0599]: no method named `into_vec` found for struct `OsString` in the current scope
   --> C:\Users\adm\.cargo\registry\src\github.com-1ecc6299db9ec823\daemonize-0.5.0\src\lib.rs:611:40
    |
611 |     CString::new(path.into_os_string().into_vec()).map_err(|_| ErrorKind::PathContainsNul)
    |                                        ^^^^^^^^ method not found in `OsString`

Some errors have detailed explanations: E0308, E0412, E0425, E0433, E0512, E0599.
For more information about an error, try `rustc --explain E0308`.
error: could not compile `daemonize` due to 51 previous errors
warning: build failed, waiting for other jobs to finish...`

**Comment by 0xor0ne** [comment]
The error is due to the Daemonize crate which is Unix specific.

Now that dependency is included only on non Windows targets. By checking out the latest version you should be able to build it on Windows (on Windows however the server option `-d` is not available).

You can now execute the server side on a terminal running powershell:

```bash
recmd.exe srv -p 6666
```

and execute commands:

```bash
recmd.exe snd -i 1.2.3.4 -p 6666 -c 'powershell.exe -Command Get-ChildItem -Path /'
```

Note however that Windows testing and support is very limited. If something does not work and you need to do advanced stuff you will probably need to do your own modification to `src/cmd.rs`
